CREATE DATABASE UDTMDT;
USE UDTMDT;

-- TẠO BẢNG 
CREATE TABLE KhachHang(
MaKH INT PRIMARY KEY AUTO_INCREMENT,
TenKH VARCHAR(100) NOT NULL,
Email VARCHAR(150)
);

CREATE TABLE DonHang(
MaDH INT PRIMARY KEY AUTO_INCREMENT,
MaKH INT NOT NULL,
FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
NgayDat DATE
);

CREATE TABLE SanPham(
MaSP INT PRIMARY KEY AUTO_INCREMENT
);


CREATE TABLE ChiTietDonHang(
MaDH INT NOT NULL,
FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH),
MaSP INT NOT NULL,
FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),
SoLuong INT
);

INSERT INTO KhachHang(TenKH,Email)
VALUES ('NGUYEN VAN A','ABC@GMAIL.COM'),
('PHAN VAN B','BCD@GMAIL.COM');

INSERT INTO DonHang(MaKH,NgayDat)
VALUES (1, '2020-11-09'),
(2,'2021-08-01');

ALTER TABLE SanPham ADD COLUMN tensanpham VARCHAR(100);

INSERT INTO SanPham(tensanpham) 
VALUES ('T-SHIRT'),
('PANTS');

INSERT INTO ChiTietDonHang(MaDH,MaSP,SoLuong)
VALUES (1,1,2),
(2,1,1);

SELECT * FROM ChiTietDonHang;

