CREATE DATABASE QLCH;
USE QLCH;

CREATE TABLE SanPham(
MaSP INT PRIMARY KEY,
TenSP VARCHAR(100) NOT NULL,
Gia DECIMAL(10,2),
SoLuongTon INT DEFAULT 0
);

-- THEM COT MOI MoTa (TEXT)
ALTER TABLE SanPham ADD COLUMN MoTa TEXT;

-- THEM 3 SP VÀO BANG
INSERT INTO SanPham(MaSP,TenSP,Gia,SoLuongTon,MoTa)
VALUES (1,'ÁO',100,15,'CHẤT LIỆU LỤA'),
(2,'QUẦN',150,10,'CHẤT LIỆU JEAN'),
(3,'ÁO DÀI',500,1,'CHẤT LIỆU LỤA');

SELECT * FROM SanPham
WHERE Gia > 50.000;