CREATE DATABASE QuanLyCuaHang;
USE QuanLyCuaHang;

CREATE TABLE KhachHang(
MaKH INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
TenKH VARCHAR(50) NOT NULL UNIQUE,
NgaySinh DATE,
DiaChi VARCHAR(100)
);

-- CHÈN 3 BẢN GHI VÀO BẢNG
INSERT INTO KhachHang(TenKH,NgaySinh,DiaChi)
VALUES
('NGUYEN VAN A', '1995-12-8','QUANG TRI'),
('TRAN VAN B', '1997-10-12','DA NANG'),
('PHAM DINH C', '1999-09-07','TT - HUE');

SELECT * FROM KhachHang;