CREATE DATABASE TMĐT;
USE TMĐT;


-- TẠO BẢNG DANH MỤC VÀ SẢN PHẨM
CREATE TABLE DanhMuc(
MaDM INT PRIMARY KEY,
TenDM VARCHAR(100)
);

CREATE TABLE SanPham(
MaSP INT PRIMARY KEY,
TenSP VARCHAR(100) NOT NULL,
Gia DECIMAL(10,2),
MaDM INT NOT NULL,
FOREIGN KEY (MaDM) REFERENCES DanhMuc(MaDM)
);

-- CHÈN 3 BẢN GHI MẪU VÀO BẢNG DanhMuc VÀ SanPham

INSERT INTO DanhMuc(MaDM,TenDM)
 VALUES
 (1, 'LIVING ROOM'),
 (2, 'KITCHEN'),
 (3,'BED ROOM');
 
 INSERT INTO SanPham(MaSP,TenSP,Gia,MaDM) 
 VALUES 
 (1,'GIƯỜNG NGỦ',10000,3),
 (2,'BẾP GAS',5000,2),
 (3,'TV',30000,1);
 
 SELECT * FROM SanPham
 WHERE MaDM = 1;